### PR TITLE
2D Platformer Demo Added

### PR DESCRIPTION
**Pull request by guilhermehto**
As I said yesterday, I'm PRing so you can check the problems that I'm having. 
Set `snap` to true on the player to do so. 

There are still some things missing like animations, music and increase the size of the map :) 

I'm creating this PR as a draft.

### CODE REVIEW

**Comment by NathanLovato** [comment]
After a quick look at the project, your player should use the new sync to physics option, and the moving platform's animation player should also use physics process and not process. Doing so already prevents the character from working entirely, which is a sign that the implementation needs to change.

I'll do an empty test project to try out snapping and these new features.

**Comment by NathanLovato** [comment]
The issues you face come from how you're lerping vectors around, applying gravity, and storing the result from `move_and_slide` as the character's new velocity. This makes the velocity change constantly to non-zero vectors, even when the character is still.

I've got working code here, the only thing I can't get to work is the `motion/sync_to_physics` property: the character always slides over the moving platform.

Here's my code for the character (NB: no need for the shoot mechanic)

```gdscript
export var snap := false
export var move_speed := 250
export var jump_force := 500
export var gravity := 900
export var slope_slide_threshold := 50.0

var velocity := Vector2()

func _physics_process(delta: float) -> void:
	var direction_x = Input.get_action_strength("move_right") - Input.get_action_strength("move_left")
	velocity.x = direction_x * move_speed

	if Input.is_action_just_pressed("jump") and snap:
		velocity.y = -jump_force
		snap = false
	velocity.y += gravity * delta
	
	var snap_vector = Vector2(0, 32) if snap else Vector2()
	velocity = move_and_slide_with_snap(velocity, snap_vector, Vector2.UP, slope_slide_threshold)

	var just_landed := is_on_floor() and not snap
	if just_landed:
		snap = true
```

**Comment by guilhermehto** [comment]
> After a quick look at the project, your player should use the new sync to physics option, 

Only the platform has to be synced. The player is already synced since we are moving it using `_physics_process()`. That's the approached showed in this [blog post](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody)

>and the moving platform's animation player should also use physics process and not process. Doing so already prevents the character from working entirely, which is a sign that the implementation needs to change.

By using physics process on the animation player the platform breaks and the player starts to slide like crazy. It's the same effect of turning sync to physics off.

**Comment by guilhermehto** [comment]
There's an issue when you stop running on a slope, the character jumps because of the y velocity returned from `move_and_slide`
image

**Comment by guilhermehto** [comment]
@NathanLovato should be good to merge, let me know if there's anything missing/that could be improved 😊

**Comment by NathanLovato** [comment]
Thanks!

**Pull request merged**
